# Generated by Django 5.2.1 on 2025-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', '게시물'), ('guestbook', '방명록'), ('portfolio', '포트폴리오')], default='post', max_length=30),
        ),
    ]
